CREATE TYPE "requirement_status" AS ENUM (
  'satisfaz',
  'conforme',
  'parcialmente_conforme',
  'nao_conforme',
  'nao_aplica'
);

CREATE TABLE "institutes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "processes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "type" text NOT NULL,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "sections" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL,
  "process_id" int,
  "code" text,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "subsections" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL,
  "section_id" int,
  "code" text,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "requirements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subsection_id" int,
  "manualRequirement" text,
  "description" text,
  "level" int,
  "evidence" text,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "followUps" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "institute_id" int,
  "lastVisit" date,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "followUps_requirements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "followUp_id" int,
  "requirement_id" int,
  "status" requirement_status,
  "observation" text,
  "completed" bool DEFAULT false,
  "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp
);

CREATE TABLE "users"{
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL,
}

ALTER TABLE "sections" ADD FOREIGN KEY ("process_id") REFERENCES "processes" ("id");

ALTER TABLE "subsections" ADD FOREIGN KEY ("section_id") REFERENCES "sections" ("id");

ALTER TABLE "requirements" ADD FOREIGN KEY ("subsection_id") REFERENCES "subsections" ("id");

ALTER TABLE "followUps" ADD FOREIGN KEY ("institute_id") REFERENCES "institutes" ("id");

ALTER TABLE "followUps_requirements" ADD FOREIGN KEY ("followUp_id") REFERENCES "followUps" ("id");

ALTER TABLE "followUps_requirements" ADD FOREIGN KEY ("requirement_id") REFERENCES "requirements" ("id");
